In [1]:
# numphy: numerical python
import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [2]:
arr1 = np.array([23,12,56,78])
arr1

array([23, 12, 56, 78])

In [3]:
arr1.ndim
# ndim: to check the dimension of an array

1

In [4]:
arr1.shape
# shape: will return the shape of an array

(4,)

In [5]:
arr1.dtype

dtype('int32')

In [7]:
arr2 = np.array([[24,56,34,54],[45,56,23,12],[13,31,26,41]])
arr2

array([[24, 56, 34, 54],
       [45, 56, 23, 12],
       [13, 31, 26, 41]])

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(3, 4)

In [13]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones((6,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.ones((6,4)) - 6

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [19]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [20]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [23]:
np.eye(4,4) * 3

array([[3., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 3.]])

In [27]:
np.eye(4,5) + 10

array([[11., 10., 10., 10., 10.],
       [10., 11., 10., 10., 10.],
       [10., 10., 11., 10., 10.],
       [10., 10., 10., 11., 10.]])

In [28]:
np.linspace(11,70)
# linspace return evenly spaced numbers over a specific interval

array([11.        , 12.20408163, 13.40816327, 14.6122449 , 15.81632653,
       17.02040816, 18.2244898 , 19.42857143, 20.63265306, 21.83673469,
       23.04081633, 24.24489796, 25.44897959, 26.65306122, 27.85714286,
       29.06122449, 30.26530612, 31.46938776, 32.67346939, 33.87755102,
       35.08163265, 36.28571429, 37.48979592, 38.69387755, 39.89795918,
       41.10204082, 42.30612245, 43.51020408, 44.71428571, 45.91836735,
       47.12244898, 48.32653061, 49.53061224, 50.73469388, 51.93877551,
       53.14285714, 54.34693878, 55.55102041, 56.75510204, 57.95918367,
       59.16326531, 60.36734694, 61.57142857, 62.7755102 , 63.97959184,
       65.18367347, 66.3877551 , 67.59183673, 68.79591837, 70.        ])

In [29]:
np.linspace(9,40,19)

array([ 9.        , 10.72222222, 12.44444444, 14.16666667, 15.88888889,
       17.61111111, 19.33333333, 21.05555556, 22.77777778, 24.5       ,
       26.22222222, 27.94444444, 29.66666667, 31.38888889, 33.11111111,
       34.83333333, 36.55555556, 38.27777778, 40.        ])

In [36]:
arr3 = np.arange(-8,200)
arr3

array([ -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,
         5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
       122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
       135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
       148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160,
       161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 17

In [34]:
arr4 = np.arange(1,200,4)
arr4

array([  1,   5,   9,  13,  17,  21,  25,  29,  33,  37,  41,  45,  49,
        53,  57,  61,  65,  69,  73,  77,  81,  85,  89,  93,  97, 101,
       105, 109, 113, 117, 121, 125, 129, 133, 137, 141, 145, 149, 153,
       157, 161, 165, 169, 173, 177, 181, 185, 189, 193, 197])

In [37]:
arr5 = np.random.randint(10,50)
arr5

43

In [39]:
np.random.seed(5)
arr6 = np.random.randint(10,80,100)
arr6

array([71, 26, 18, 72, 37, 40, 17, 25, 63, 37, 54, 75, 57, 40, 28, 19, 51,
       72, 11, 26, 15, 68, 10, 14, 46, 61, 37, 41, 12, 78, 48, 29, 28, 17,
       40, 72, 21, 77, 75, 65, 13, 37, 39, 43, 17, 26, 24, 41, 19, 48, 57,
       26, 15, 44, 55, 69, 34, 23, 41, 42, 54, 15, 24, 57, 10, 17, 26, 74,
       18, 54, 47, 15, 32, 62, 79, 70, 39, 45, 30, 59, 42, 23, 28, 62, 32,
       68, 59, 14, 46, 51, 30, 42, 20, 41, 25, 32, 19, 73, 24, 76])

In [40]:
arr7 = arr6.reshape(10,10)
arr7

array([[71, 26, 18, 72, 37, 40, 17, 25, 63, 37],
       [54, 75, 57, 40, 28, 19, 51, 72, 11, 26],
       [15, 68, 10, 14, 46, 61, 37, 41, 12, 78],
       [48, 29, 28, 17, 40, 72, 21, 77, 75, 65],
       [13, 37, 39, 43, 17, 26, 24, 41, 19, 48],
       [57, 26, 15, 44, 55, 69, 34, 23, 41, 42],
       [54, 15, 24, 57, 10, 17, 26, 74, 18, 54],
       [47, 15, 32, 62, 79, 70, 39, 45, 30, 59],
       [42, 23, 28, 62, 32, 68, 59, 14, 46, 51],
       [30, 42, 20, 41, 25, 32, 19, 73, 24, 76]])

In [42]:
arr7[4,4]

17

In [43]:
arr7 = arr7.flatten()
arr7

array([71, 26, 18, 72, 37, 40, 17, 25, 63, 37, 54, 75, 57, 40, 28, 19, 51,
       72, 11, 26, 15, 68, 10, 14, 46, 61, 37, 41, 12, 78, 48, 29, 28, 17,
       40, 72, 21, 77, 75, 65, 13, 37, 39, 43, 17, 26, 24, 41, 19, 48, 57,
       26, 15, 44, 55, 69, 34, 23, 41, 42, 54, 15, 24, 57, 10, 17, 26, 74,
       18, 54, 47, 15, 32, 62, 79, 70, 39, 45, 30, 59, 42, 23, 28, 62, 32,
       68, 59, 14, 46, 51, 30, 42, 20, 41, 25, 32, 19, 73, 24, 76])

In [44]:
np.sum(arr7)

4040

In [45]:
np.mean(arr7)

40.4

In [46]:
np.median(arr7)

39.5

In [47]:
np.var(arr7)

401.4200000000001

In [48]:
np.sqrt(arr7)

array([8.42614977, 5.09901951, 4.24264069, 8.48528137, 6.08276253,
       6.32455532, 4.12310563, 5.        , 7.93725393, 6.08276253,
       7.34846923, 8.66025404, 7.54983444, 6.32455532, 5.29150262,
       4.35889894, 7.14142843, 8.48528137, 3.31662479, 5.09901951,
       3.87298335, 8.24621125, 3.16227766, 3.74165739, 6.78232998,
       7.81024968, 6.08276253, 6.40312424, 3.46410162, 8.83176087,
       6.92820323, 5.38516481, 5.29150262, 4.12310563, 6.32455532,
       8.48528137, 4.58257569, 8.77496439, 8.66025404, 8.06225775,
       3.60555128, 6.08276253, 6.244998  , 6.55743852, 4.12310563,
       5.09901951, 4.89897949, 6.40312424, 4.35889894, 6.92820323,
       7.54983444, 5.09901951, 3.87298335, 6.63324958, 7.41619849,
       8.30662386, 5.83095189, 4.79583152, 6.40312424, 6.4807407 ,
       7.34846923, 3.87298335, 4.89897949, 7.54983444, 3.16227766,
       4.12310563, 5.09901951, 8.60232527, 4.24264069, 7.34846923,
       6.8556546 , 3.87298335, 5.65685425, 7.87400787, 8.88819